### ISSUE TITLE
Implementar caso de uso "Realizar Compra"

### ISSUE THREAD

**Issue by CristianLeit** [CristianLeit/PPADS-Project#1]

**Comment by marcospsoliveira** [comment]
Nome do caso de uso: Realizar Compra

Ator principal: Cliente

Pré-condições: O cliente deve estar autenticado no sistema.

Fluxo básico:

1. O cliente navega pelo catálogo de produtos e seleciona os produtos desejados.
2.O cliente adiciona os produtos ao carrinho de compras.
3.O cliente seleciona o método de pagamento.
4.O. sistema redireciona o cliente para a página do provedor de serviços de pagamento.
5.O cliente fornece as informações de pagamento.
6.O provedor de serviços de pagamento processa o pagamento.
7.O sistema confirma o pagamento e atualiza o status da compra.
8.O sistema envia um e-mail de confirmação da compra para o cliente.
9.O sistema remove os produtos do carrinho de compras.

Fluxo alternativo: No passo 4, se ocorrer algum erro ao redirecionar o cliente para a página do provedor de serviços de pagamento, o sistema exibe uma mensagem de erro.

**Comment by marcospsoliveira** [comment]
Nome do caso de uso: Realizar Compra

Ator principal: Cliente

Pré-condições: O cliente deve estar autenticado no sistema.

Fluxo básico:

1. O cliente navega pelo catálogo de produtos e seleciona os produtos desejados.
2.O cliente adiciona os produtos ao carrinho de compras.
3.O cliente seleciona o método de pagamento.
4.O. sistema redireciona o cliente para a página do provedor de serviços de pagamento.
5.O cliente fornece as informações de pagamento.
6.O provedor de serviços de pagamento processa o pagamento.
7.O sistema confirma o pagamento e atualiza o status da compra.
8.O sistema envia um e-mail de confirmação da compra para o cliente.
9.O sistema remove os produtos do carrinho de compras.

Fluxo alternativo: No passo 4, se ocorrer algum erro ao redirecionar o cliente para a página do provedor de serviços de pagamento, o sistema exibe uma mensagem de erro.
