### ISSUE TITLE
Implementar caso de uso "Cadastrar Produto"

### ISSUE THREAD

**Issue by CristianLeit** [CristianLeit/PPADS-Project#2]

**Comment by marcospsoliveira** [comment]
Nome do caso de uso: Cadastrar Produto

Ator principal: Gerente de Negócios

Pré-condições:

O gerente de negócios deve estar autenticado no sistema com permissões de cadastro de produtos.
Fluxo básico:

O sistema apresenta a tela de cadastro de produto.
O gerente de negócios registra os dados do produto, incluindo nome, descrição, preço, imagens, etc.
O sistema valida os dados do produto.
O sistema salva o produto no banco de dados.
O sistema exibe uma mensagem de confirmação de cadastro do produto.
Fluxo alternativo: 3a. Se alguma informação do produto estiver incorreta, o sistema exibirá uma mensagem de erro. 3a.1 O sistema volta para a tela de cadastro de produto e as informações introduzidas são mantidas. 4a. Se ocorrer algum erro na inserção do produto no banco de dados, o sistema exibe uma mensagem de erro.

Pós-condições:

O produto é salvo no banco de dados.
